### PR TITLE
Permissions Scope

### PR DESCRIPTION
**Pull request by Callum-Newton**
Implemented the ability to be able to pass through permissions in the options with a failsafe for basic permissions.

Implementation of Scopes:
https://www.instagram.com/developer/authentication/

Scopes:
https://www.instagram.com/developer/authorization/

### CODE REVIEW

**Review by butane — CHANGES_REQUESTED** [review]
I would very much like to see two minor changes to your code.
1. Line 25 (instagram_client.js) from your code will give an error if the user called the requestCredential function with options parameter set to null. Check how its done here: https://github.com/meteor/meteor/blob/devel/packages/facebook/facebook_client.js#L28
1. Instead of "options.permissions", I would prefer "options.requestPermissions" to be consistent with other core meteor OAuth packages.

**Comment by Callum-Newton** [comment]
I've renamed it to requestPermissions and updated the PR to include the if statement

**Review by butane — COMMENTED** [review]
Line 35 - Did you miss a '+' and ';' ?

**Comment by Callum-Newton** [comment]
Fixed, forgot them because I'm used to template literals now

**Review by butane — APPROVED** [review]

**Pull request merged**
